import { Epilogue, Playfair } from "next/font/google";
import { ThemeProvider } from "@/components/ui/theme-provider";
import "./globals.css";

const epilogueSans = Epilogue({
  variable: "--font-epilogue",
  subsets: ["latin"],
});

const playfair = Playfair({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${epilogueSans.variable} ${playfair.variable} antialiased`}>

        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disbaleTransitionOnChange>
          {children}
        </ThemeProvider>
        
      </body>
    </html>
  );
}
